# Definición de servicios
services:
  inmobiliaria-services:
  # Configuración para construir la imagen del contenedor desde el contexto actual
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/inmobiliaria:latest
    # Nombre del contenedor
    container_name: inmobiliaria
    # Configuración para reiniciar siempre el contenedor
    restart: always
    # Configuración de redes
    networks:
      - luis
    # Volumen de almacenamiento
    volumes:
      - volume-path:/back-end/src/path

# Definición de redes
networks:
  # Red llamada 'luis'
  luis:
    # Configuración para usar una red externa existente
    external: true

volumes:
  volume-path: