name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      # =========================
      # Front-End ENV
      # =========================
      - name: Create app/.env
        run: |
          cat > app/.env <<EOL
          VITE_APP_END_POINT=${{ secrets.VITE_APP_END_POINT }}
          VITE_APP_URL=${{ secrets.VITE_APP_URL }}
          VITE_APP_IMAGE=${{ secrets.VITE_APP_IMAGE }}
          VITE_APP_ENV=${{ secrets.VITE_APP_ENV }}
          VITE_APP_VERSION=${{ secrets.VITE_APP_VERSION }}
          EOL

      # =========================
      # Back-End ENV
      # =========================
      - name: Create server/.env
        run: |
          cat > server/.env <<EOL
          PORT=${{ secrets.PORT }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_PORT=${{ secrets.DB_PORT }}
          TZ=${{ secrets.TZ }}
          ENVIRONMENT=${{ secrets.ENVIRONMENT }}
          EOL

      # =========================
      # AWS Credentials
      # =========================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # =========================
      # Login ECR
      # =========================
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # =========================
      # Build Docker Image
      # =========================
      - name: Build Docker image
        run: |
          docker compose build

      # =========================
      # Tag Image
      # =========================
      - name: Tag Docker image
        run: |
          docker tag inmobiliaria-image \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/inmobiliaria:latest

      # =========================
      # Push Image
      # =========================
      - name: Push Docker image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/inmobiliaria:latest

  deploy-to-runs-on:
    name: Deploy to Run.sh
    runs-on: self-hosted
    needs: build-and-push

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      NAME_SERVICE: ${{ matrix.environment }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download image since ECR
        run: docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/inmobiliaria:latest

      - name: Create and execute container in production
        run: docker compose -f docker-compose.prod.yml up -d

      - name: Delete local images
        run: docker image prune -af || true

  clean-ecr-images:
    name: Clear up old images in ECR
    runs-on: ubuntu-latest
    needs: deploy-to-runs-on
    
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Delete old images from ECR
        run: |
          REPO="inmobiliaria"

          aws ecr list-images --repository-name "$REPO" \
            --query "imageIds[?type(imageTag)==null || imageTag!='${TAG}']" \
            --output json > images.json

          COUNT=$(jq length images.json)
          if [ "$COUNT" -gt 0 ]; then
            echo "🗑️ Cleaning up $COUNT old images from $REPO..."
            aws ecr batch-delete-image --repository-name "$REPO" --image-ids file://images.json
          else
            echo "✅ There are no old images to delete from $REPO."
          fi